# 工作流的名称
name: Build and deploy 
# 从工作流生成的工作流运行的名称
run-name: Deploy by @${{ github.actor }}  
# 触发工作流的事件
on:
  push:
    branches: [ main ] # 当 main 分支有新的推送时，此工作流会被启动。
  workflow_dispatch: # 或者手动触发工作流时，此工作流会被启动。
# 当前流程要执行的任务
jobs:
  build:
    # 这部分指定了作业将在 ubuntu-latest 环境下运行。
    runs-on: ubuntu-latest
    # 每个任务下的运行步骤，短横杠 - 表示一个步骤，从上至下依次执行。
    steps:
      - name: checkout # 检出代码
        uses: actions/checkout@v2 # 使用 actions/checkout action 检出代码到工作空间。

      # 这一步安装 Node.js v20。
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true
          cache: 'pnpm' # 启用 pnpm 缓存

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 将 pnpm 添加到 PATH
      - name: Add pnpm to PATH
        run: echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      # 缓存 pnpm node_modules
      - name: Cache dependencies
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 安装依赖 pnpm
      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      # 运行构建脚本
      - name: Run Build Script
        run: pnpm run build
        
      - name: Configure Git
        run: |
          git config --global user.name "tunaizi"
          git config --global user.email "tunaizi@163.com"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG_CONFIG }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: blog